[
    {
        "data": {
            "model_name": "whisper_medium"
        },
        "error": "InferenceException",
        "message": "InferenceException(model_name=whisper_medium)",
        "stacktrace": "\u001b[36mray::ServeReplica:asr_deployment:WhisperDeployment.handle_request_with_rejection()\u001b[39m (pid=235100, ip=10.101.102.28, actor_id=8f6ee00a3ab3623db1c6120f01000000, repr=<ray.serve._private.replica.ServeReplica:asr_deployment:WhisperDeployment object at 0x74eb89d30340>)\n    async for result in self._call_user_generator(\n  File \"/home/mobius/.cache/pypoetry/virtualenvs/aana-loqJzHhH-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 460, in _call_user_generator\n    raise e from None\n  File \"/home/mobius/.cache/pypoetry/virtualenvs/aana-loqJzHhH-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 1150, in call_user_method\n    raise e from None\nray.exceptions.RayTaskError: \u001b[36mray::ServeReplica:asr_deployment:WhisperDeployment.handle_request_with_rejection()\u001b[39m (pid=235100, ip=10.101.102.28)\n  File \"/home/mobius/.cache/pypoetry/virtualenvs/aana-loqJzHhH-py3.10/lib/python3.10/site-packages/ray/serve/_private/utils.py\", line 168, in wrap_to_ray_error\n    raise exception\n  File \"/home/mobius/.cache/pypoetry/virtualenvs/aana-loqJzHhH-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 1131, in call_user_method\n    result = await self._handle_user_method_result(\n  File \"/home/mobius/.cache/pypoetry/virtualenvs/aana-loqJzHhH-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 1038, in _handle_user_method_result\n    async for r in result:\n  File \"/home/mobius/mobiuslabs/aana_sdk/aana/deployments/base_deployment.py\", line 144, in wrapper_generator\n    raise cache[\"exception\"]\naana.exceptions.runtime.InferenceException: InferenceException(model_name=whisper_medium)"
    }
]